### ISSUE TITLE
Voicemail doesnt work.

### ISSUE THREAD

**Issue by wotelljm** [ugoviti/izdock-izpbx#26] opened 2021-10-18 14:31 UTC
When attempting to check voicemail the Asterisk cli indicates no ap Voicemail main for Ext. XXXX.
You can login to comedian mail using *98 but *97 just returns no app VoicemailMain for ext. Whatever.

**Comment by ugoviti** [comment] 2021-11-20 14:35
I can't reproduce this issue... still valid?

closing right now... reopen please if not solved

**Closed by ugoviti** 2021-11-20 14:35 UTC

**Comment by idovitz** [comment] 2022-06-30 20:50
Got this too.

Steps to reproduce:
Followed steps in readme.md to setup PBX. Created extention 1 with voicemail enabled. Called *97 and got in asterisk logs:

_WARNING[2506][C-00000002] pbx.c: No application 'VoiceMailMain' for extension (from-internal, *97, 10)_
